enableGlobalCache: false

nodeLinker: node-modules

logFilters:
  - text: "api@workspace:api provides graphql (p201cc) with version 15.8.0, which doesn't satisfy what graphql-relay requests"
    level: 'discard'
  - code: 'YN0060'
    level: 'error'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
